services:
  projectwatb-app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      rede-compartilhada:
        aliases:
          - projectwatb-app

networks:
  rede-compartilhada:
    external: true
    name: minha-rede-compartilhada