version: "3.8"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      - rede-compartilhada

networks:
  rede-compartilhada:
    external: true
    name: minha-rede-compartilhada